const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');
if (!fs.existsSync(localesDir)) {
  fs.mkdirSync(localesDir, { recursive: true });
}

const ja = {
  // Common & Status
  title: "REMNANTS OF THE ABYSS",
  btn_lang: "[ English ]",
  btn_manual: "[ マニュアル ]",
  status_title: "STATUS",
  command_title: "COMMAND",
  log_title: "LOG",
  level: "Lv",
  exp: "EXP",
  hp: "HP",
  mp: "MP",
  en: "En",
  item: "ITEM",
  cost: "COST",
  close: "閉じる",

  // Manual
  manual_title: "マニュアル - 基本システム",
  manual_explore: "【探索と帰還】",
  manual_explore_desc: "ダンジョンの奥へ進むほど敵は強力になりますが、得られる記憶（アイテム）の質も向上します。帰還するには現在の深度×100 Enが必要です。縁が足りない場合、強制的な「業の取り立て」が発生します。",
  manual_cost: "【コストと呪い】",
  manual_cost_desc: "強力な記憶ほど高いコストを持ちます。自身のキャパシティを超える装備はできません。呪われた記憶は一度装備すると外せなくなります。",
  manual_penalty: "【業の取り立て（ペナルティ）】",
  manual_penalty_desc: "帰還時に縁が足りない場合、装備していない記憶を没収されます。没収する記憶すらない場合、最大HPが恒久的に減少する致命的なペナルティを受けます。",

  // Town Commands
  cmd_status: "自身の状態を確認する",
  cmd_inv: "インベントリ（装備）",
  cmd_priest: "破戒僧の庵（鑑定・強化）",
  cmd_enma: "閻魔の計量所（売却）",
  cmd_buyback: "記憶を買い戻す",
  cmd_stash: "倉庫（縁の預入・保管）",
  cmd_system: "システム（セーブ・ロード）",
  cmd_inn: "微睡みの寝床（宿屋）",
  cmd_dungeon: "薄暗い迷宮へ向かう",

  // Explore Commands
  cmd_explore: "探索を進める",
  cmd_magic: "魔法（スキル）",
  cmd_return: "街へ戻る (帰還コスト: {{cost}} En)",
  cmd_fight: "戦う",
  cmd_run: "逃げる",
  cmd_next: "次へ",

  // App Overlays
  overlay_status: "自身の状態を確認",
  overlay_inv: "インベントリ（装備）",
  overlay_priest: "破戒僧の庵",
  overlay_enma: "閻魔の計量所",
  overlay_buyback: "記憶を買い戻す",
  overlay_stash: "倉庫",
  overlay_system: "システム",
  overlay_inn: "微睡みの寝床",
  overlay_dungeon: "迷宮の入り口",
  overlay_magic: "魔法（スキル）",

  // Inventory / MemoryDetail
  inv_select: "リストからアイテムを選択してください",
  inv_unidentified: "未鑑定の記憶",
  detail_rarity: "レアリティ:",
  detail_category: "カテゴリ:",
  detail_cost: "コスト:",
  detail_equip_effect: "装備効果",
  detail_spell: "付与魔法",
  detail_mp_cost: "消費MP:",
  btn_equip: "装備する",
  btn_unequip: "外す",
  btn_identify: "鑑定する ({{cost}} En)",
  btn_sell: "売却 (+{{price}} En)",
  btn_buyback_act: "買戻 (-{{price}} En)",
  buyback_left: "あと{{dives}}回",
  
  // Stash & Shop
  stash_hand: "手持ちの縁:",
  stash_vault: "倉庫の縁:",
  btn_deposit: "縁を預ける",
  btn_withdraw: "縁を引き出す",
  stash_maxed: "倉庫は最大まで拡張済み",
  stash_expand: "倉庫を拡張する ({{cost}} En)",

  // Hooks - Economy
  eco_inv_full: "所持枠が一杯です。",
  eco_identified: "未鑑定の記憶を {{cost}} Enで鑑定しました。",
  eco_no_en: "縁が足りません。",
  eco_no_unidentified: "未鑑定の記憶がありません。",
  eco_stash_no_en: "倉庫の縁が足りません。",
  eco_withdrew: "{{amount}} 縁を引き出しました。",
  eco_deposited: "{{amount}} 縁を預けました。",
  eco_stash_max: "これ以上倉庫を拡張できません。",
  eco_stash_expanded: "倉庫を拡張しました。最大容量: {{size}}",
  eco_sold: "{{name}} を {{price}} Enで売却しました。",
  eco_bought: "{{name}} を {{price}} Enで買い戻しました。",
  eco_buyback_exp: "買い戻し期限が切れています。",
  eco_rested: "宿屋で身体を休め、HPとMPが全回復しました。",

  // Hooks - Memory
  mem_equip_full: "装備枠が一杯です。",
  mem_cost_over: "コストオーバーです。（現在: {{current}}, 上限: {{max}}）",
  mem_installed: "{{name}} をインストールしました。",
  mem_not_found: "指定された記憶が見つかりません。",
  mem_cursed: "呪われているため、外すことができません！",
  mem_removed: "{{name}} を取り外しました。",

  // Hooks - GameLoop
  gl_start_explore: "街を出て、深度 {{depth}} から探索を開始した。",
  gl_encounter: "魔物と遭遇した！ (深度: {{depth}})",
  gl_encounter_boss: "【警告】圧倒的な絶望が立ち塞がる……。失われた『俺』の影が現れた！（深度: {{depth}}）",
  gl_nothing: "何も見つからなかった……。 (深度: {{depth}})",
  gl_drop: "敵を打ち倒し、{{name}} を獲得した！",
  gl_no_drop: "敵を打ち倒したが、めぼしいものは無かった。",
  gl_flee_success: "逃走に成功した！",
  gl_flee_fail: "逃走に失敗した！",
  gl_enemy_atk: "{{name}} の攻撃！ {{dmg}} のダメージを受けた！",
  gl_dead: "HPが尽き、倒れた……。",
  gl_levelup: "レベルアップ！ レベルが {{level}} になった！",
  gl_return: "街へ帰還した。",
  gl_karma: "縁が足りず、業の強制取り立てが発生した……。",
  gl_lost_item: "{{name}} を失った。",
  gl_hp_down: "最大HPが 5 減少した……。",
  gl_no_mp: "（MPが足りない！）",
  gl_no_equip: "（装備していない！）",
  gl_magic_atk: "魔法を発動！ 敵に大ダメージ！",
  gl_magic_heal: "魔法を発動！ HPが {{heal}} 回復した。",
  gl_magic_atkup: "魔法を発動！ 攻撃力がアップした！",
  gl_magic_defup: "魔法を発動！ 防御力がアップした！",
  gl_magic_spdup: "魔法を発動！ 素早さがアップした！",
  gl_magic_return: "帰還魔法を発動！ 縁を消費せずに街へ帰還した！",
  
  // Dungeon
  dungeon_select: "どの深度から探索を開始しますか？",
  dungeon_from: "深度 {{depth}} から",
  
  // System
  sys_save: "SLOT {{slot}} にセーブしました。",
  sys_load: "SLOT {{slot}} からロードしました。",
  sys_delete: "SLOT {{slot}} のデータを削除しました。",
  sys_no_data: "NO DATA",
  sys_confirm_save: "SLOT {{slot}} にセーブしますか？",
  sys_confirm_load: "SLOT {{slot}} のデータをロードしますか？",
  sys_confirm_del: "SLOT {{slot}} のデータを削除しますか？"
};

const en = {
  title: "REMNANTS OF THE ABYSS",
  btn_lang: "[ 日本語 ]",
  btn_manual: "[ Manual ]",
  status_title: "STATUS",
  command_title: "COMMAND",
  log_title: "LOG",
  level: "Lv",
  exp: "EXP",
  hp: "HP",
  mp: "MP",
  en: "En",
  item: "ITEM",
  cost: "COST",
  close: "Close",

  manual_title: "Manual - Basic Systems",
  manual_explore: "[ Exploration & Return ]",
  manual_explore_desc: "The deeper you go, the stronger the enemies, but the better the memories (items) you find. Returning costs Depth × 100 En. If you lack En, the Karma Debt Collector will take what you owe.",
  manual_cost: "[ Cost & Curses ]",
  manual_cost_desc: "Powerful memories have higher costs. You cannot equip beyond your Capacity. Cursed memories cannot be removed once equipped.",
  manual_penalty: "[ Karma Debt (Penalty) ]",
  manual_penalty_desc: "If you cannot afford the return cost, unequipped memories will be confiscated. If you have nothing to give, your Max HP will be permanently reduced.",

  cmd_status: "Check Status",
  cmd_inv: "Inventory & Equip",
  cmd_priest: "Priest Hut (Identify/Upgrade)",
  cmd_enma: "Enma Station (Sell)",
  cmd_buyback: "Buyback Memories",
  cmd_stash: "Stash (En Vault)",
  cmd_system: "System (Save/Load)",
  cmd_inn: "Slumber Inn (Rest)",
  cmd_dungeon: "Enter the Labyrinth",

  cmd_explore: "Explore Further",
  cmd_magic: "Magic (Skills)",
  cmd_return: "Return to Town (Cost: {{cost}} En)",
  cmd_fight: "Fight",
  cmd_run: "Flee",
  cmd_next: "Next",

  overlay_status: "Status",
  overlay_inv: "Inventory (Equip)",
  overlay_priest: "Priest Hut",
  overlay_enma: "Enma Station",
  overlay_buyback: "Buyback Memories",
  overlay_stash: "Stash",
  overlay_system: "System",
  overlay_inn: "Slumber Inn",
  overlay_dungeon: "Labyrinth Entrance",
  overlay_magic: "Magic (Skills)",

  inv_select: "Please select an item from the list",
  inv_unidentified: "Unidentified Memory",
  detail_rarity: "Rarity:",
  detail_category: "Category:",
  detail_cost: "Cost:",
  detail_equip_effect: "Equip Effects",
  detail_spell: "Enchanted Spell",
  detail_mp_cost: "MP Cost:",
  btn_equip: "Equip",
  btn_unequip: "Unequip",
  btn_identify: "Identify ({{cost}} En)",
  btn_sell: "Sell (+{{price}} En)",
  btn_buyback_act: "Buyback (-{{price}} En)",
  buyback_left: "{{dives}} dives left",

  stash_hand: "En on hand:",
  stash_vault: "Stashed En:",
  btn_deposit: "Deposit En",
  btn_withdraw: "Withdraw En",
  stash_maxed: "Stash fully expanded",
  stash_expand: "Expand Stash ({{cost}} En)",

  eco_inv_full: "Inventory is full.",
  eco_identified: "Identified memory for {{cost}} En.",
  eco_no_en: "Not enough En.",
  eco_no_unidentified: "No unidentified memories.",
  eco_stash_no_en: "Not enough En in stash.",
  eco_withdrew: "Withdrew {{amount}} En.",
  eco_deposited: "Deposited {{amount}} En.",
  eco_stash_max: "Stash cannot be expanded further.",
  eco_stash_expanded: "Stash expanded. Max capacity: {{size}}",
  eco_sold: "Sold {{name}} for {{price}} En.",
  eco_bought: "Bought back {{name}} for {{price}} En.",
  eco_buyback_exp: "Buyback period has expired.",
  eco_rested: "Rested at the inn. HP and MP fully restored.",

  mem_equip_full: "Equip slots are full.",
  mem_cost_over: "Cost limit exceeded. (Current: {{current}}, Max: {{max}})",
  mem_installed: "Equipped {{name}}.",
  mem_not_found: "Specified memory not found.",
  mem_cursed: "Cannot remove a cursed memory!",
  mem_removed: "Removed {{name}}.",

  gl_start_explore: "Left town, started exploration from Depth {{depth}}.",
  gl_encounter: "Encountered a monster! (Depth: {{depth}})",
  gl_encounter_boss: "[WARNING] Overwhelming despair blocks your path... The Lost Shadow of 'Self' appeared! (Depth: {{depth}})",
  gl_nothing: "Found nothing... (Depth: {{depth}})",
  gl_drop: "Defeated the enemy and obtained {{name}}!",
  gl_no_drop: "Defeated the enemy, but found nothing of value.",
  gl_flee_success: "Successfully fled!",
  gl_flee_fail: "Failed to flee!",
  gl_enemy_atk: "{{name}} attacked! Took {{dmg}} damage!",
  gl_dead: "HP reached 0. You have fallen...",
  gl_levelup: "Level Up! Reached level {{level}}!",
  gl_return: "Returned to town.",
  gl_karma: "Not enough En. The Karma Debt Collector has arrived...",
  gl_lost_item: "Lost {{name}}.",
  gl_hp_down: "Max HP permanently decreased by 5...",
  gl_no_mp: "(Not enough MP!)",
  gl_no_equip: "(Not equipped!)",
  gl_magic_atk: "Cast Magic! Dealt heavy damage to the enemy!",
  gl_magic_heal: "Cast Magic! Restored {{heal}} HP.",
  gl_magic_atkup: "Cast Magic! Attack power increased!",
  gl_magic_defup: "Cast Magic! Defense power increased!",
  gl_magic_spdup: "Cast Magic! Speed increased!",
  gl_magic_return: "Cast Return! Escaped to town without spending En!",

  dungeon_select: "Which depth will you start from?",
  dungeon_from: "From Depth {{depth}}",

  sys_save: "Saved to SLOT {{slot}}.",
  sys_load: "Loaded from SLOT {{slot}}.",
  sys_delete: "Deleted data in SLOT {{slot}}.",
  sys_no_data: "NO DATA",
  sys_confirm_save: "Save to SLOT {{slot}}?",
  sys_confirm_load: "Load data from SLOT {{slot}}?",
  sys_confirm_del: "Delete data in SLOT {{slot}}?"
};

fs.writeFileSync(path.join(localesDir, 'ja.ts'), \`export const ja = \${JSON.stringify(ja, null, 2)};\n\`);
fs.writeFileSync(path.join(localesDir, 'en.ts'), \`export const en = \${JSON.stringify(en, null, 2)};\n\`);
console.log('Dictionaries generated.');
